addon/components/docs-demo/x-live-example/component.js

Finally a much smaller PR!
I am writing all of my docs using markdown, and one thing I noticed is that my live-example snippets weren't being shown. 
The first reason is that ember-code-snippet doesn't look for snippets in .md files :( 
https://github.com/ef4/ember-code-snippet/pull/41
The second reason is that the live-example component only looks for snippets generated with a `.hbs` extension. This PR is to address that.
So I'm just being a madonna here and really wanting to use markdown for my docs, but if I just switch over to .hbs I can literally finish writing v1 of my docs and it's great!

Live-Example Component Support .md Files

---

addon/components/docs-viewer/x-search/component.js

* When searching, don't link to routes that dont exist (was throwing glimmer error)
* Don't load search index until didInsertElement, fix for addons that support fastboot
For #50

Search fixes

---

index.js

We have discovered that exporting addon to app breaks
the build when the expected folders do not exist.
This PR simply checks that a folder exists before processing its contents.

Skips non existing paths when exporting addon to app

---

index.js

When building the documentation for an addon with ember-cli-addon-docs,
the paths to ember-cli-addon-docs do not resolve correctly.

Resolves paths correctly in treeForApp

---

addon/services/docs-routes.js

Add one more replace for query params and make quotes more consistent!
For https://github.com/ember-learn/ember-cli-addon-docs/issues/62

Allow to use query params on docs routes

---

.travis.yml
package.json

I took a look at our Travis config, and it turned out we're still running all the ember-try scenarios in each of the first two stages because `yarn test` aliases `ember try:each`. This update:
- updates the locked/floating dependencies phases to only run the test suite a single time
- runs the node test suite for each of those (before it was being caught because there's an ember-try scenario for it, but that's not really the ideal way to manage it)
- removes the `ember-default` try scenario from the versioned tests stage, since that should be equivalent to our 'floating dependencies' run
Before: [~33 minutes](https://travis-ci.org/ember-learn/ember-cli-addon-docs/builds/347354105) of wall clock time
After: [~14 minutes](https://travis-ci.org/ember-learn/ember-cli-addon-docs/builds/34808477 …

Speed up Travis

---

tests/dummy/app/pods/docs/quickstart/template.md

Fix confusion in the quickstart guide

---

tests/dummy/app/pods/docs/quickstart/template.md

To prevent confusion for new Ember users.

Clarify favicon location

---

addon/components/api/x-class/component.js
addon/components/api/x-class/template.hbs
addon/components/api/x-component/component.js
addon/components/api/x-component/template.hbs
addon/components/api/x-index/style.scss
addon/components/api/x-index/template.hbs
addon/helpers/type-signature.js
addon/models/class.js
addon/models/component.js
addon/utils/computed.js
package.json
sandbox/app/components/esdoc-component.js
sandbox/app/components/yuidoc-component.js
yarn.lock

This PR adds filtering of members for classes and components that allows
users to filter out private, protected, inherited, and deprecated
members. In the case of components, users can also filter out `internal`
properties - everything besides Yields and Arguments.
Filters only appear if there is something to filter, and by default
they are enabled (unchecked), so users should see the minimal public API
of the class.
The complexity of the filters is definitely not ideal, but at the moment
I'm unsure if pushing that complexity into the object model (e.g. by
adding `publicFields`, `privateFields`, `staticPublicFields`,
`staticPrivateFields`, etc directly to models) as part of the build step
will help much.

[feat] API filtering

---

lib/broccoli/docs-filter.js
lib/models/plugin-registry.js
package.json
sandbox/app/components/esdoc-component.js
sandbox/app/components/yuidoc-component.js

Currently we're having lots of things be double documented
by ESDoc, which is making it really hard to debug issues.
This adds a quick option @documenter tag that'll filter
out files based on what they declare they _should_ be
documented by.

[feat] Allow specifying a documenter

---

ember-cli-build.js

Before:
```
File sizes:
- dist/assets/dummy-85b90b99235e74788ee6f2d9e1a8ae0f.js: 154.27 KB (33.92 KB gzipped)
- dist/assets/vendor-5e6d3ca90736b58a05177e7786ece4f5.js: 1.67 MB (442.97 KB gzipped)
```
After:
```
File sizes:
- dist/assets/dummy-85b90b99235e74788ee6f2d9e1a8ae0f.js: 154.27 KB (33.92 KB gzipped)
- dist/assets/vendor-1ae6d4df0c293cba4de9787f665208aa.js: 1.58 MB (413.65 KB gzipped)
```
This saves 29,32KB after gzip.

Stop including jquery and shims in the output

---

addon/components/docs-viewer/x-nav/component.js
lib/broccoli/docs-compiler.js

* Ensures that we can correctly create a nested directory in the event that a package's name is `@myscope/package-name`.  This was breaking because the `@myscope` directory wasn't being created before.
* Ensures that we don't rely on matching names to be at the start of a package's name to allow for a scope to be at the beginning
Fixes https://github.com/ember-learn/ember-cli-addon-docs/issues/46, but I'm honestly not 100% sure if this is the best approach.
Fixes #111

support for scoped packages

---

index.js

I don't think this is the root cause of #106, but it can't be helping. In general having this flag turned on in production is bad for performance because it opts the addon into things like linting that the host shouldn't be concerned with.

Don't ship with `isDevelopingAddon: true`

---

index.js
package.json
yarn.lock

This will fix #106. The underlying cause looks to be https://github.com/nodejs/node/issues/15683, so  anyone on APFS who's not using watchman is likely to run into this.
The problem in our specific case is that we're triggering a watch on the root of the repo in question, which means it includes all of `tmp` and `node_modules`, both of which are potentially pretty big.
@pzuraq I know you're on your way out, but if you have a chance to take a peek, I'll cut a bugfix release if the changes look good to you.

Avoid triggering a watch on the addon root

---

addon/components/docs-header/component.js
addon/components/docs-header/template.hbs
addon/components/docs-viewer/x-nav/component.js
addon/utils/computed.js

* Used in two places, on of which was broken. Split out into a separate function that both locations can import
* Only the `docs-header` used the `addonLogo` property, all other references to the same feature use `logo`. The documentation also used `logo` but the implementation was setting `addonLogo` and ignoring the provided `logo` property. Now it's all just `logo`

Clean up `logo` code

---

addon/components/docs-demo/template.hbs
addon/tailwind/config/modules.css

Generally, `<a>` should be avoided with `href="#"` since it's not "semantically correct" to use a link when no navigation occurs. A `<button>` is better semantically. It looks the same, just without the navigation.

Avoid using an <a> without navigation

---

addon/components/docs-viewer/x-main/component.js
index.js

- More generic matching (removes assumption that the file is within the `pods` directory)
- Fixes some references to the original `docs.api.class` route and updates them to use `docs.api.item`

Fix template edit link

---

addon/components/docs-demo/component.js
addon/utils/computed.js

Duplicate members were being added directly to the public member array
on each toggle. This PR ensures that there is a new array created each
time the computed is run.
Closes #138

[bugfix][API] Prevent duplicate members from filters

---

tests/dummy/app/pods/docs/quickstart/template.md

It's called 'Introduction' in the nav block above, so should probably match here as well.

fix(quickstart): index header should match the nav name

---

addon/components/api/x-import-path/component.js
addon/components/docs-header/component.js
addon/components/docs-header/template.hbs
addon/components/docs-viewer/x-main/component.js
addon/components/docs-viewer/x-nav/component.js
addon/routes/docs.js
addon/services/project-version.js
addon/utils/computed.js
index.js
tests/dummy/mirage/config.js

This lightens the size of the payload we're adding to `config/environment` and fixes #123

Parse package repository correctly

---

addon/components/docs-header/version-selector/template.hbs
addon/services/project-version.js
index.js
lib/config.js
lib/deploy/plugin.js
lib/utils/read-config.js
tests/acceptance/version-selector-test.js
tests/dummy/app/pods/docs/deploying/template.md
vendor/ember-cli-addon-docs/404.html

Fixes #133 and provides a solid foundation for adding the `/v/` namespace and moving the `latest` deploy into the root. This has the side effect of fixing the flicker in the project version selector when the app boots, since it no longer needs to wait for `versions.json` to be able to populate its initial label.

Allow for customizing the expected root URL of a docs site.

---

addon/components/docs-header/search-box/template.hbs
addon/components/docs-header/search-result/component.js
addon/components/docs-header/search-results/template.hbs
addon/services/docs-search.js
index.js
lib/broccoli/search-indexer.js
tests/acceptance/sandbox/api/components-test.js
tests/pages/api/class.js
tests/pages/api/module.js
tests/pages/base.js
tests/pages/guide.js

This meant that words like `docs-snippet` were being indexed as `docs` and `snippet`, but would be searched for as `docs-snippet`.
I'm not sure that method of sharing state is particularly great, but we can't `import` from `lib/broccoli`, or `require` from `addon/services`.
There's some good suggestions over here on how search could be further improved with a Lunr pipeline: https://github.com/olivernn/lunr.js/issues/296

Fix bug where the token separators used in the search component and the search indexer were inconsistent

---

addon/components/docs-keyboard-shortcuts/component.js
addon/components/docs-viewer/component.js
addon/controllers/application.js
addon/keyboard-config.js

When using some of the old examples on the demo page, I found that the page would change location if I hit J or K. This was quite annoying, so this is an attempt to fix that problem.
Although live examples have been removed, I think this is worth adding. Snippets may have demos with form inputs, and it would be messed up to have the page changed unexpectedly when typing.

Prevent keyboard shortcuts from running when the document's active element is a form element

---

lib/utils/compile-markdown.js
tests-node/unit/utils/compile-markdown-test.js

This ensures that _all_ escaped characters are unescaped when rendering
markdown. Should minimize the impact Marked has on our templates. I've
also opened an issue with Marked directly to see if we can upstream
this.

[bugfix] Prevents all Marked escaping in plain text

---

lib/config.js
lib/deploy/plugin.js
tests/dummy/app/pods/docs/deploying/template.md
vendor/ember-cli-addon-docs/index.html

Supporting root deploys looks like it'll only be a small piece of work on top of this, so I'm inclined to say we should land that as well (in a separate PR) to help sweeten the bitter pill of this migration...
@samselikoff here are my notes from migrating my deploy playground addon over, if you get the chance to give this a try with storefront at some point:
- checkout gh-pages (or go to the worktree directory)
- ~open 404.html and change `segmentCount` from 2 to 3~ no longer necessary now that this depends on the `configurable-root-url` branch
- open `index.html` and change the redirect to `./v/latest`
- create a directory called `v` and move each deployed tag/branch directory inside (strip the leading `v` off tag directories)
- for each deployed tag/branch, go open index.html and …

Move deploys under a version namespace

---

lib/deploy/plugin.js
vendor/ember-cli-addon-docs/404.html

This PR eliminates the need to redirect from `/` to `/latest` by deploying the latest version at the top level instead of under `/latest`, moving all other versions under a special `/versions` path (like `/versions/beta` or `/versions/v1.0.0`), and adapting the redirection logic to handle both cases (top-level app vs versioned which can be distinguished by the presence of the “versions” name immediately after the true root URL).
This is a breaking change for existing sites, which leads to some questions for discussion:
- Are people OK with making this new layout default, vs having a config option that would let existing sites stay as they are?
- Should we just do a major release and give manual upgrade instructions?
- Should we try to make an automatic upgrade (it’s hard in general …

move latest to top-level URL

---

package.json
yarn.lock

This version has many bugfixes, and we're already using it in ember-animated docs, so this eliminates a conflict for us.
There were no breaking changes.
(authored while pairing with @ef4)

Upgrade ember-svg-jar

---

addon/components/docs-viewer/x-main/template.hbs
addon/services/docs-routes.js
tests/acceptance/docs-route-test.js
tests/dummy/app/pods/sandbox/template.hbs
tests/dummy/app/router.js

(authored while pairing with @ef4)
This makes the docs-route service more tolerant of pages with their own internal URL structure. For example, we're using this in ember-animated to have a page that includes an outlet in order to demonstrate cross-route animations.

Allow child routes under docs pages

---

package.json
yarn.lock

To be compatible with Broccoli 1 & 2
This PR would remove some of these deprecation warnings:
```
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: 
[API] Warning: Plugin uses .read/.rebuild API: 
```

Upgrade ember-code-snippet

---

lib/utils/compile-markdown.js
package.json
yarn.lock

This PR tweaks the `title()` method of the `HBSRenderer` in [lib/utils/compile-markdown.js](https://github.com/22a/ember-cli-addon-docs/blob/b75247734aff43f30a63f51e090f8d60a857ba02/lib/utils/compile-markdown.js#L124-L127) to only add a title attribute to the html snippet when the passed `title` argument is truthy. 
This prevents adding `null` (and perhaps also `undefined`, but I haven't encountered that yet) title attributes to `a` tags, such as this ([visible here](https://ember-learn.github.io/ember-cli-addon-docs/docs)):
---
This PR also bumps the [`marked`](https://github.com/markedjs/marked) dependency from `^0.3.12` to `^0.5.0` for no particular reason other than to keep it up to date - I don't feel strongly about this and I'm happy to remove this change from the PR if you'd …

Omit <a> title attribute if title is null

---

package.json
yarn.lock

This is a PR for Issue https://github.com/ember-learn/ember-cli-addon-docs/issues/242
It allows addon docs to accept a wider range of Ember Data versions. This way it won't conflict with the host addon's data dependency.

Ember data 2 or 3

---

tests/dummy/app/pods/docs/deploying/template.md

When I tried to use this config to disable the addon-docs deployment plugins I got the following warning in my terminal.
```
Your config has referenced the following unknown plugins or aliases in `config.pipeline.disabled`:
- addon-docs
```
It appears that simply using `addon-docs` is not a valid alias for disabling the `ember-cli-addon-docs` deployment plugins.
In the below screenshot if I put a breakpoint inside the [ember-cli-deploy code](https://github.com/ember-cli-deploy/ember-cli-deploy/blob/b6df8fb3d7d7e798092cab5721b921abe0435dee/lib/models/plugin-registry.js#L101) you can see the alias that appears.
I'm imagining `ember-cli-deploy-git` and `ember-cli-deploy-git-ci` appear as `git` and `git-ci` as the `ember-cli-deploy-` gets snipped.

Updated disable deploy docs

---

blueprints/ember-cli-addon-docs/index.js

This adds a prompt so you can select ESDoc or YUIDoc when the blueprints run.

Add prompt for ESDoc/YUIDoc

---

index.js
package.json
yarn.lock

This should fix #239, essentially by moving our `treeForPublic` implementation to `postprocessTree('all')` instead.
For auto-import this wasn't a viable solution, since `postprocessTree('all')` doesn't run for nested addons, but since we know we'll always be a direct dependency of the dummy app (at least in the current world), we don't have that issue and can avoid [needing to monkey-patch anything](https://github.com/ef4/ember-auto-import/blob/ec307965ebbce248b27fb611ee0cd309056452af/ts/auto-import.ts#L95-L112).

Use postprocessTree('all') for compatibility with Ember CLI 3.4

---

package.json
test-apps/new-addon/package.json
yarn.lock

Follow up from  PR #252. The default blue print removed `ember-cli-shims`. While doing the upgrade I added it back to make tests pass, but I realized that we don't need that at all as we are using the same version of everything from the addon and the test app.

Remove unnecessary ember-cli-shims

---

.gitattributes

This apparently worked for ember-auto-import: https://github.com/ef4/ember-auto-import/blob/master/.gitattributes

Inform to github that scripts/parallel is vendored

---

lib/utils/compile-markdown.js
tests-node/unit/utils/compile-markdown-test.js

With version `0.6.0` and using angle bracket syntax inside your markdown files will actually brake the build.
This is **not** working:
```
<DocsDemo @class="docs-demo" as |demo|>
{{#demo.example name='demo.hbs'}}
<FooBar @label="fubar"/>
{{/demo.example}}
{{demo.snippet 'demo.hbs'}}
</DocsDemo>
```
This patch fixes the parser to not only handle curlies but also angle brackets :)

Fix markdown parser

---

tests/dummy/app/pods/docs/quickstart/template.md

Hello! I was trying to set up the addon and ran into a few issues where the demo documentation for the quickstart template didn't seem to quite match up with the template that's rendered in the demo. This PR updates the code snippets so that the UI created by copying the snippets matches the UI in the demo.
Hopefully this is helpful! Thanks for building this awesome addon 😄

Change example snippets in quickstart to match the demo UI layout

---

tests/dummy/app/pods/docs/deploying/template.md

Add sentence explaining the necessity of tagged releases for the `gh-pages` root to work.

Update example URL to include `/versions`

---

package.json

Should be ablve to remove this if/when https://github.com/salesforce/tough-cookie/pull/141 is merged.
Fixes https://github.com/ember-learn/ember-cli-addon-docs/issues/298

Pin tough-cookie to support Node 6

---

package.json
yarn.lock

This version includes https://github.com/ebryn/ember-component-css/pull/308 which fixes this addon for Ember 3.6+

Update ember-component-css to fix 3.6 deprecation

---

addon/components/docs-header/link/template.hbs
addon/tailwind/components/docs-brand-colors.css
addon/tailwind/config/colors.js
test-apps/new-addon/tests/acceptance/smoke-test-test.js
test-apps/new-addon/tests/dummy/app/styles/app.css
test-apps/new-addon/tests/dummy/app/templates/application.hbs
test-apps/new-addon/tests/dummy/app/templates/index.md
yarn.lock

This implementation has some debt. We can decide if we want the feature now or want to figure out a cleaner solution now.
If we could just use CSS Custom Properties, this would be super clean as the Tailwind config var would just be `--brand-primary`. However, there's not full browser support, so I wanted to provide a fallback. The fallback is to define a vanilla `color: ` (or background-color or border-color) property before the variable use.
I used a Tailwind Component to insulate the rest of the codebase from this knowledge, that way we can continue to use `docs-color-brand` and have it work everywhere.
I had to use `!important` because components come before utilities, so a `docs-text-grey-dark` was overriding the brand color. If/when we get the router service in to improve the docs …

Use CSS Custom Property for brand color

---

addon/components/docs-header/version-selector/component.js
tests/acceptance/version-selector-test.js

`removeObjects` mutates the original array

lastest and master are not in version selector on second open

---

lib/utils/compile-markdown.js
tests-node/unit/utils/compile-markdown-test.js

Fixes #306 
Basically I updated the regexes with negative lookbehinds and lookaheads. From my quick research, negative lookbehinds were introduced in node 6, so we should be good. lookaheads were always supported, afaik.

support opening tags inside backticks

---

addon/components/docs-demo/template.hbs

This just wraps the nav and snippet in a div.
This way it's very easy to have horizontal demos by just adding the `docs-flex docs-flex-row` classes to the docs-demo component. Results in something like this:
Doesn't affect any existing vertical demos.
If an `horizontal=true` flag is desired, I can add it. It could add those classes to the container and also apply a left border on the snippet.

wrap nav and snippet in a div 

---

tests/dummy/app/pods/docs/quickstart/template.md

The Ember Router Scroll addon is now installed by default.
Closes #203

Removed outdated optional step: "Better scrolling"

---

.eslintrc.js
package.json
tests-node/unit/deploy/plugin-test.js
tests-node/unit/navigation-index-generator/test.js
tests-node/unit/utils/compile-markdown-test.js
tests-node/unit/utils/update-demo-url-test.js
yarn.lock

As briefly discussed in https://github.com/ember-learn/ember-cli-addon-docs/pull/343#issuecomment-479818068, moving to mocha as the test library for node tests will allow us to take advantage of other packages (`ember-cli-*` utils, for instance) that internally use mocha. This opens the door to leveraging more prior art in writing more robust tests for things like blueprints, etc.
This PR converts all tests in `tests-node` to use `mocha`/`chai`.

Converts node tests to use mocha instead of qunit.

---

index.js
package.json
yarn.lock

Right now we trash any configuration the host app has for ember-auto-import to avoid having it try and include `qunit` in our own tests. This isn't necessary now that we're using mocha for node tests and don't need `qunit` in our dependencies, but this config should have been in our `ember-cli-build.js` to begin with so it wouldn't interfere with the host.

Don't blow away the host's auto-import config

---

blueprints/docs-page/index.js
package.json
tests-node/fixtures/blueprints/docs-subnav.hbs
tests-node/fixtures/blueprints/docs.hbs
tests-node/unit/blueprints/docs-page-test.js
yarn.lock

As promised, I've circled back and updated the node tests to include blueprint tests for `docs-page` now that our node tests use mocha/chai. 
This PR:

Adding tests for docs-page blueprint

---

package.json
yarn.lock

This PR contains the latest version of ember-responsive that fixes broken tests on latest beta & canary builds of ember addons using this addon. 
Related PR: https://github.com/freshbooks/ember-responsive/pull/145

Update ember responsive to fix broken tests on ember beta & canary builds

---

.travis.yml

This PR doesn't allow addon-docs to fail in Ember beta.
The default config for ember addons [will not allow beta to fail]( https://github.com/ember-cli/ember-addon-output/blob/master/.travis.yml#L31). Since addons are the most likely consumer of addon docs it's possible that they could pull in a version of addon docs that fails in Ember beta (and potentially breaks their travis builds).
Related: https://github.com/ember-learn/ember-cli-addon-docs/pull/363

Remove beta from allowed failures

---

package.json
yarn.lock

Actually does what it says on #363. ember-responsive had the fix in 3.0.1 which they didn't publish to npm until yesterday (#363 updated it to 3.0.0 😅)

Upgrade ember-responsive to fix broken tests on ember beta & canary builds

---

tests/dummy/app/pods/docs/quickstart/template.md

Change "An" -> "Add". Looked like that might be a typo.
Thanks for creating AddonDocs!

Minor change to quickstart docs

---

addon/components/docs-keyboard-shortcuts/component.js
addon/components/docs-keyboard-shortcuts/template.hbs

Adds a keyUp listener for 'Escape' that dismisses the shortcuts modal
when invoked.
Also fixes an unrelated inconsistency in quote style in the
keyboard-shortcuts component.
<kbd>Esc</kbd> seems to be a common shortcut for other modals (e.g. [bootstrap](https://getbootstrap.com/docs/4.0/components/modal/#options) and [ember-modal-dialog](https://github.com/yapplabs/ember-modal-dialog#keyboard-shortcuts)).

Use "Escape" key to dismiss Keyboard Shortcuts modal

---

lib/broccoli/docs-compiler/navigation-index-generator.js

When working in an addon with a scoped package name (eg: @scope-name/package-name), the "API REFERENCE", "Components" navigation section is incorrectly generated (it shows Class Name). The expected outcome is {{component-name}}.
The link generated is also messed up:
Expected: https://user-or-org.github.io/repo-name/docs/api/components/component-name
Actual: https://user-or-org.github.io/repo-name/docs/api/modules/@scope-name/package-name/components/component-name~Class%20Name
This is because of how ember-addon-docs assumes the root of the package. 
Fixes #374

Fix scoped packages bug when nav items are generated

---

addon/initializers/route-anchor-jump.js

* avoid making reopen inside `initialize` (it should only be done once **ever** not once per application)
* avoid destructuring from `location` when it is not defined (e.g. FastBoot contexts)
* ensure that the super result is properly returned (previously we would drop any promises returned from afterModel 😱)
Fixes #417

Refactor route anchor jump system

---

addon/initializers/route-anchor-jump.js

Using `scheduleOnce` with an anonymous function [doesn't actually schedule only once](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-incorrect-calls-with-inline-anonymous-functions.md), since a new function is created on every invocation. This PR just changes to use `schedule`, which I believe is fine in this case.

Change scheduleOnce to schedule

---

.dependabot/config.yml

Would you accept a Dependabot config to automate dependencies upgrade?
This config runs dependabot **on a weekly basis** (not to be too verbose). It can also be run on a montly basis if you prefer.
This config should also **auto-merge in-range updates**. To enable that feature, you'll have to visit https://app.dependabot.com/accounts/ember-cli-addon-docs/settings and tick the box `Allow auto-merging to be enabled on projects`.
To enable **squash and merge** for dependabot PRs, you'll have to untick the box `Create a merge commit if a PR is merged by Dependabot`.
With the `version_requirement_updates: auto` option, Dependabot should:
- increase versions in the `devDependencies`
- widen ranges in the `dependencies`

dependabot: Add a config

---

index.js
tests/dummy/app/pods/docs/build-options/template.md
tests/dummy/app/pods/docs/template.hbs
tests/dummy/app/router.js

Since this PR: https://github.com/ef4/ember-code-snippet/pull/59/files it is possible to indicate the extensions to look for snippets. This PR just add the option to use the functionality.
I added a new section to the documentation to let people know that this new option exists.

enhancement: Add config options to indicate the file extensions that ember-code-snippet needs to use

---

addon/adapters/-addon-docs.js
addon/components/api/x-class/component.js
addon/components/api/x-section/component.js
addon/components/docs-header/component.js
addon/components/docs-header/search-box/component.js
addon/components/docs-header/search-results/component.js
addon/components/docs-header/version-selector/component.js
addon/components/docs-hero/component.js
addon/components/docs-snippet/component.js
addon/components/docs-viewer/x-main/component.js
addon/components/docs-viewer/x-nav/component.js
addon/routes/docs.js
addon/services/docs-search.js
addon/services/project-version.js
index.js
package.json
tests/acceptance/sandbox/api/components-test.js
tests/acceptance/version-selector-test.js
tests/dummy/mirage/config.js
yarn.lock

This makes it possible to separate your docs application from your addon's dummy app. Fixes #383.
The way it works is:
- you're still required to keep both the addon and the docs app in the same repo (so we don't need to worry about separately versioning each)
- but they can be peers or subdirectories of each other
- in your docs application you add ember-cli-addon-docs
- in your docs application you must set the `documentingAddonAt` option to point at the path of the actual addon. This option is what opts you into the new behavior, otherwise nothing should be changed.
As a side-effect of refactoring the way "Edit this page" links work, I think I also fixed them for API-docs pages in all addon docs sites (not just ones using this new architecture).

Support standalone docs apps

---

index.js
test-apps/new-addon/tests/acceptance/snippets-test.js
test-apps/new-addon/tests/dummy/app/router.js
test-apps/new-addon/tests/dummy/app/templates/snippets.hbs

Fixes #420
Closes #342 
Based on info in [nosloush's PR](https://github.com/ember-learn/ember-cli-addon-docs/pull/342), especially [dfreeman's suggestion](https://github.com/ember-learn/ember-cli-addon-docs/pull/342#issuecomment-517229597)

Snippets support angle bracket invocation

---

addon/components/docs-snippet/component.js

[This change](https://github.com/ember-learn/ember-cli-addon-docs/commit/5fb1cc8093ef530610345aa3938f2133112e91dd#diff-f7fa78c2855306dcc677ce08403e4a7bR84-R87) broke _Copy button_ and [this added test](https://github.com/ember-learn/ember-cli-addon-docs/pull/421/files#diff-e9530505b3b89edc49ce62e319dd4131) broke the tests.

Fix copy snippet button

---

lib/deploy/plugin.js

This might be not the right place to do the replacement, but it does the thing and unblocks my deploys.

rootURL: replace backslashes with forward slashes, fixes #427

---

addon/components/docs-snippet/template.hbs
index.js
test-apps/new-addon/tests/acceptance/snippets-test.js
test-apps/new-addon/tests/dummy/app/templates/snippets.hbs

In #421 we landed support for using angle-bracket invocation with `<DocsDemo>` and `<DocsSnippet>`, but it unfortunately didn't handle non-block usage that referenced a snippet defined elsewhere, e.g.:
```hbs
<DocsSnippet @name="my-snippet.hbs" />
```
Code like ☝️ would wind up capturing everything after that in the file as "my-snippet.hbs" instead of honoring the `/>`.

Support non-block `<DocsSnippet>` invocation

---

addon/styles/components/_docs-md.scss

Fix docs heading styles due to Tailwind's v1 preflight

---

tests/dummy/app/pods/docs/standalone-apps/template.md
tests/dummy/app/pods/docs/template.hbs
tests/dummy/app/router.js

This mostly just copies over Ed's instructions.
Closes #445

Document using standalone apps

---

addon/utils/compile-markdown.js
tests-node/unit/utils/compile-markdown-test.js
tests/dummy/app/pods/docs/quickstart/template.md

Fixes #402. 
cc @dfreeman @samselikoff @@rwwagner90.

[Markdown compiler] Fix compact paragraphs with code blocks

---

index.js
package.json
yarn.lock

The version of ember-composable-helpers currently being used provides an array helper.
ember@next has started erroring when it encounters built in helpers being clobbered.
ember-composable-helpers@3 has removed the array helper and upgraded to octane.
As an alternative to the commit, we could try to get a new version of ember-composable-helpers@2 cut that excludes the array helper for ember <= 3.8.

fix array helper clobbering built in helper

---

addon/serializers/class.js
addon/serializers/component.js
addon/serializers/module.js
addon/serializers/project.js

by rexporting -addon-docs serializer
see https://deprecations.emberjs.com/ember-data/v3.x#toc_ember-data:default-serializers
fixes https://github.com/ember-learn/ember-cli-addon-docs/issues/439

fix deprecation ember-data:default-serializer

---

tests/dummy/app/pods/docs/quickstart/template.md

`docs/template.hbs` is the incorrect file name, the file it asks you to create should match the title of the `docs-snippet`

Fix doc typo

---

tests/dummy/app/pods/docs/usage/template.md

Any developer can get autocomplete and documentation tips for addons used in projects if addons has addon-docs documentation.
https://github.com/lifeart/els-addon-docs

tip: Visual Studio Code addon-docs integration

---

tests/dummy/app/pods/docs/quickstart/template.md

This reflects how the addon-docs site itself is structured and is also consistent with the fact that the Quickstart guide later asks you to generate an index page, which would get added as a sub-item in the nav under the Introduction section. It's also convenient, because it subtly introduces the concept of a nav section, which isn't covered anywhere else in the Quickstart.

Use section instead of item for Introduction

---

package.json
yarn.lock

ref #552 
I am unsure if peer dependencies is a strict versio or loose range.  Might be worthwhile to make it `3.x - and above` if so.

Minimum 3.x series for ember-data addon

---

.travis.yml
config/ember-try.js
package.json
yarn.lock

We've just released ember-concurrency 2.0.0-beta.1. It's a largely API-compatible re-engineering of ember-concurrency's internals to support tracked properties and decouple from Ember (shedding EmberObject, etc.). As a popular library which depends on ember-concurrency, it would be nice for `ember-cli-addon-docs` to support both 1.x and 2.x versions concurrently so that folks can upgrade the version of ember-concurrency in their applications at their leisure without waiting for all the add-ons they use to switch over to a newer version (and risk leaving folks who cannot upgrade yet behind.)
This PR adds some scenarios to ember-try to enable testing against both major releases and relaxes the version restriction.
The build fails for beta and canary, but does not appear related to these …

Add test for both ember-concurrency v1 and v2

---

addon/router.js
package.json
test-apps/new-addon/package.json
yarn.lock

Update to ember-router-scroll v4

---

addon/helpers/type-signature.js
addon/utils/compile-markdown.js
test-apps/new-addon/tests/dummy/app/controllers/route-using-compile-markdown.js

I noticed the deprecation messages when importing htmlSafe from `@ember/string`. The messages are still there due to t[his issue though](https://github.com/emberjs/ember.js/issues/19393). But that should be resolved in the next ember-source patch release.

Import htmlSafe from `@ember/template`

---

.github/workflows/ci-cd.yml
package.json
test-apps/new-addon/package.json
yarn.lock

* Bumps ember-wormhole to 0.6.0. This was causing a mismatch between babel 6 & 7 in consuming apps, which created build errors.
* Drops transitive dependency on an older version of ember-cli-htmlbars
* This will require a major release, since ember-modal-dialog 4.0.0-alpha.0 has symobolically (but not technically) dropped support for <= Ember 3.19: https://github.com/yapplabs/ember-modal-dialog/pull/332
* Also drops Node 10 support, which was dropped by ember-modal-dialog: https://github.com/yapplabs/ember-modal-dialog/pull/333
Ran `yarn test:ember`, `yarn test:node`, and `yarn test:test-apps` locally to confirm no failures.

ember-modal-dialog 4.0.0-alpha.0, Drop support for <=Ember 3.19, Node 10

---

addon/components/api/x-class/template.hbs

Fix display of import path
In v2.0.0 via https://github.com/ember-learn/ember-cli-addon-docs/pull/831/files#diff-7cd3d2b711dc840f44e1d648241f814f51ffef5405f9e4b0b474f11cebb1eb37R6, a refactor was made to use `@showImportPaths` instead of `showImportPaths`, but `showImportPaths` is not an attribute but a property from `x-class` component, see https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/api/x-class/component.js#L16
___
Current behavior
New behavior
___
I really don't know if i should add some tests for this, as project is in maintenance mode and as far as i can see there is no test around that. But maybe i missed something, if you feel like we should start to add tests on these components i will add one.
___
Note that it is sure that `ember-beta` and …

fix: display of import path

---

package.json

As [@glimmer/component](https://github.com/glimmerjs/glimmer.js/tree/master/packages/%40glimmer/component) and [@glimmer/tracking](https://github.com/glimmerjs/glimmer.js/tree/master/packages/%40glimmer/tracking) are now used in the `addon` directory via this commit -> https://github.com/ember-learn/ember-cli-addon-docs/pull/934/files#diff-59d3e78aa5dff5b8d7cdf515b80e1900e1a9fc0440bb3f64a1eb98aa62af2277R1-R2
They need to be moved in dependencies, otherwise we will have this error when using v4 of this repo in an addon/app not having, for example, `@glimmer/component` in his devDeps / deps ->
```
$ ember build --environment=production
Environment: production
cleaning up...
Build Error (WebpackBundler)
ember-cli-addon-docs tried to import "@glimmer/component" in …
```

fix: move @glimmer/component and @glimmer/tracking in dependencies

---

package.json
yarn.lock

It seems the `yarn.lock` was not correctly built, when we serve the app locally and try to do a search, it throws an error
But looking at the `ember-modal-dialog` commit we use it should be ok, added one commit to downgrade `ember-modal-dialog` to 3.0.3 and one commit to use back `ember-modal-dialog#76b74f1c4b791fed5b084836c3b1c8c54836ac71` and it updates the `yarn.lock` with good dependencies, fixing the error above with the search
If i'm not wrong it should not impact app/addons consuming this repo as they will resolve `ember-modal-dialog#76b74f1c4b791fed5b084836c3b1c8c54836ac71` themselves

fix: yarn.lock with ember-modal-dialog commit

---

blueprints/ember-cli-addon-docs/index.js

When using ember-auto-import@2, it will use the `rootURL` to prefix the URLs of the injected chunks. It does this without adding a preceding slash, which means the URLs are invalid and chunks cannot be loaded. As a result, required dependencies, such as highlight.js, are not available (since they weren't loaded by the preceding chunk).

Fixes broken deployment with ember-auto-import@2

---

addon/services/docs-routes.js
package.json
yarn.lock

Reason being that it imports `@ember/routing/link-component` which has been removed in ember v4.
Replaces the helper function from this addon with a direct call to the routing service.

chore(deps): drop ember-href-to

---

addon/components/docs-link.js
package.json
yarn.lock

I think this will be required for Ember v4 compatibility

chore: import LinkComponent from `ember/legacy-built-in-components`

---

.eslintrc.js
.npmignore
babel.config.js
package.json
yarn.lock

Follow up to #1010.
I may be wrong, followed https://github.com/babel/ember-cli-babel/issues/418, https://github.com/ember-modifier/ember-modifier/issues/102 and https://github.com/ember-modifier/ember-modifier/pull/101/files
My assumption is that addons should not ship `babel.config.js` (at least yet).
Also followed what Chris did with `buildEmberPlugins()` instead of specifying only `@babel/plugin-proposal-decorators` plugin, I assume it just gives us some sort of safety net and be on pair with ember-cli-babel (at least from babel config perspective)

Add babel.config.js to .npmignore

---

package.json
tests/dummy/config/environment.js
yarn.lock

This fixes an error in Ember v4 related to built-in components import

Bump ember-keyboard from 6.0.3 to 7.0.0-beta.0

---

.github/workflows/ci-cd.yml

This will help fixing CI so we can have all the issues available and work on them in parallel rather than via try and fail approach

Set default CI config blueprints to run all builds

---

.github/workflows/ci-cd.yml

References:
* https://github.com/actions/setup-node#caching-packages-dependencies
* https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/files/.github/workflows/ci.yml
the change is to use `actions/setup-node@v2` with `cache: yarn` option

PR to speed up CI times on GitHub Actions by caching dependencies.

---

addon/components/docs-demo/index.hbs

There was a missing `this` in the DocsDemo component making it fail to compile with ember-source v4+.

Fix no implicit this deprecation in docs-demo component

---

test-apps/new-addon/tests/dummy/app/templates/index.md
tests/dummy/app/templates/docs/components/docs-hero.md
tests/dummy/app/templates/index.hbs

Not much to see here. Just doc updates since the DocsHero is already a glimmer component.

update docs hero docs

---

addon/components/modal-dialog.js

Since ember modal dialog itself uses classic components, there's little we can do here besides using native class syntax.

update modal dialog

---

addon/adapters/-addon-docs.js

Without this fix, addon docs deploys won't load correctly when using `ember-auto-import >= 2`. For me instead of loading versions.json from `https://ember-stereo.com/docs/ember-stereo.json` upon page load, it instead tried to load from `https://ember-stereo.com/ADDON_DOCS_ROOT_URL/docs/ember-stereo.json`

fix(config): use runtime config instead of embroider generated one

---

index.js
tests/dummy/app/templates/docs/standalone-apps.md

The `src` folder is a the new convention for the location of the addon source code.
This can be seen in [Porting an Addon to V2](https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md) guide as well as part of [new addon blueprint](https://github.com/embroider-build/addon-blueprint/tree/main/files/packages/__name__).
This was tested in https://github.com/ember-animation/ember-animated/pull/397

Support v2 addon format

---

.github/workflows/ci-cd.yml
README.md
package.json
test-apps/new-addon/package.json

`ember-cli-postcss` is listed in `dependencies` of this addon.
#1093 bumped `ember-cli-postcss` from 7.2.0 to 8.0.0 which is breaking change as 8.0.0 dropped support for Node.js 12.
Because of that, using `master` branch of `ember-cli-addon-docs` already requires Node.js 14 so this PR updates references to v12 so it also will be part of changelog.

Drop Node.js 12 support

---

addon/components/docs-keyboard-shortcuts/index.js

Right now, the DocsKeyboardShortcutsComponent attempts to use `this.set`
to set a property. DocsKeyboardShortcutsComponent is a Glimmer
Component, so this API is not available.  To avoid the problem, let's
use a regular assignment statement.

avoid using `this.set` (fixes #1275)

---

addon/styles/tailwind.config.js
index.js

Ember CLI Addon Docs should use system fonts by default. System fonts load quickly for users, reduce the site's coupling to 3rd party assets, and make sites privacy-friendly by default.
The Google font previously relied upon would result in Google having the ability to add cookies for that traffic, possibly placing a site out of compliance with EU and other regulations regarding user tracking without consent processes in place.
Here I've replaced (via https://github.com/Addepar/ember-table/pull/983 for the purposes of illustration):
* https://fonts.google.com/specimen/Crimson+Text
* Try it in your browser at https://opensource.addepar.com/ember-table/versions/v5.0.3/docs
with
* https://github.com/system-fonts/modern-font-stacks#old-style
* Try it in your browser at …

Swap out 3rd party font for system fonts

---

package.json
yarn.lock

This dependency was added here: https://github.com/ember-learn/ember-cli-addon-docs/pull/122
It does not seem to have been used in that PR at all, and I can't find any invocations of its features in current code, either. This appears to be an unused dependency shipped to consumers.

Remove ember-tether

---

.github/workflows/ci-cd.yml
addon/models/module.js
addon/models/project.js
config/ember-try.js

This is an attempt to fix #1466 and allow us to add `ember-cli-addon-docs` with Ember 5.* 😄

Add `inverse: null` to `hasMany` relationships

---

addon/components/docs-viewer/x-nav-list/index.hbs

noticed an issue while was working on `ember-cli-mirage`.
See https://www.ember-cli-mirage.com/versions/master/docs/api/modules/ember-cli-mirage/serializers/ember-data-serializer for reproduction - note "API Reference" > "ember-cli-mirage" > "Modules" > " serializers" is not indented properly as it should be on the same level as "ember-cli-mirage".
this was missed when `docs-viewer/x-nav-list` component was converted from `@ember/component` to `@glimmer/component` and previously `class` argument was assigned to the component container element and now just got lost.
the `class` argument passed in https://github.com/ember-learn/ember-cli-addon-docs/blob/v6.0.1/addon/components/docs-viewer/x-nav/index.hbs#L33

Forward @class argument in `docs-viewer/x-nav-list` component

---

package.json
yarn.lock

This adds `ember-tether` to the package "depencencies" and will fix #1484.

Add ember-tether to dependencies

---

.github/workflows/ci-cd.yml
addon/models/class.js
addon/models/module.js
addon/models/project.js
tests/dummy/config/ember-try.js

fix compatibility with ember-data 5

---

addon/components/docs-viewer/x-nav/index.hbs

On mobile, the navigation shows the class names because the `<button>` tag hadn't been closed correctly.

Fixed typo in <DocsViewer::XNav>

---

package.json

`@ember/string` must be a dependency as `ember-cli-addon-docs` imports it in their codebase. Currently this still works, but with v4 of `@ember/string` (v2 addon) this will break as it fully relies on `ember-auto-import`.

Fix @ember/string dependency

---

lib/deploy/plugin.js
lib/utils/find-and-replace-in-directory.js
tests-node/unit/deploy/plugin-test.js

This fixes a bug where `ADDON_DOCS_ROOT_URL` was not replaced inside chunks.

Recursively replace ADDON_DOCS_ROOT_URL

---

blueprints/ember-cli-addon-docs/index.js
tests/dummy/app/templates/docs/quickstart.md

This adds the `ember-data` dependency to the Quickstart docs. It will help address #818.

Add `ember data` dependency to the quickstart

---

addon/styles/_variables.scss
addon/styles/addon.scss
addon/styles/components/_docs-viewer-x-current-page-index.scss
addon/styles/components/_docs-viewer-x-nav.scss

This finally silences:
```
[test:ember]
[test:ember]   ╷
[test:ember] 9 │ @import './tailwind/components/docs-btn';
[test:ember]   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[test:ember]   ╵
[test:ember]     addon/styles/addon.scss#sass 9:9  root stylesheet
[test:ember]
[test:ember] DEPRECATION WARNING: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
```
Fixes: [#1673](https://github.com/ember-learn/ember-cli-addon-docs/issues/1673)

Silence sass errors

---

tests/dummy/app/templates/docs/standalone-apps.md

- Adding section does not have any isntructions.
- Should I just `ember install`? Or are there any other steps?

docs: How do I "add ecad"?

---

addon/helpers/capitalize.js
app/helpers/capitalize.js
package.json
pnpm-lock.yaml
tests/dummy/config/environment.js
tests/integration/helpers/capitalize-test.js

- This pulls @ember/string 3.1.1 into dependent project and that causes a lot of issues
- Since we have `capitalize` in @ember/string, we can just call that in our internal helper
- ~~Also bumped internal version of @ember/string to v4.x~~ -> I could not make it work, next step
- Also pins portal target for ember-tether to correct scope for testing so that assertions can work correctly
Fixes #1666

fix: Remove ember-cli-string-helpers
