README.md
=> Add a short description of what the project is

.gitignore, addon/components/docs-viewer/x-nav-item/component.js, addon/services/docs-routes.js, package.json, tests/acceptance/docs-route-test.js
Simple test for now, would have caught a rendering bug that showed up when using ember try @ 2.8.
=> Add acceptance test

addon/components/docs-demo/x-example/component.js
Hi!
We wanted to be able to link to specific examples in a give page. Would this addition be ok?
=> Add id to example component

addon/adapters/application.js
Did a bit of digging into #62 and I think it's going to be easier to use ajax service for the time being than try to solve those issues, so decided to fix it real quick
=> [bugfix] Replace fetch with ajax service

addon/services/project-version.js
This should get the build "green" again
=> Fix linting error

blueprints/ember-cli-addon-docs/index.js
Fixes https://github.com/ember-learn/ember-cli-addon-docs/issues/103
=> Stop publishing "config/addon-docs.js"

addon/components/docs-viewer/component.js, addon/components/docs-viewer/x-search/component.js, addon/services/docs-search.js, config/ember-try.js
This is necessary to be able to document addons that don't have jquery.
=> Stop using jquery

package.json
=> [update] Officially drop Node v4

lib/broccoli/docs-compiler.js, sandbox/app/utils/esdoc-module.js, sandbox/app/utils/yuidoc-module.js
@pzuraq You may have already fixed this locally for your work with ember-decorators, but since @lupestro was asking about it in Slack yesterday I thought I'd go ahead and put this up.
=> Fix links to module items and provide sample docs

addon/components/api/x-import-path/component.js, addon/components/api/x-import-path/template.hbs, addon/components/docs-viewer/x-nav-item/component.js, addon/components/docs-viewer/x-nav/template.hbs, addon/routes/docs/api/item.js, ember-cli-build.js, index.js, lib/broccoli/docs-compiler.js, tests/acceptance/sandbox/api/helpers-test.js
This changes the way that we link to modules in order to make it more
generic. The main difference here is that we no longer assume that the
project name has any relation to the module itself, instead we always
use the fully-qualified module name as its id, its link, and title.
There are some pros and cons to this approach:
* Pros
* More inline with JS/modules as a whole - Since we base everything on
the full module name, we aren't basing it on arbitrary Ember-only
concepts, like the Addon/App folders, etc. The build system now just
receives a tree with a module structure, and assumes that it is the
correct, canonical structure.
* More self-documenting - users can know at a glance what the import
path for an item is just by looking at the sidebar
* Supports documenting multiple addons in …
=> [refactor] Simplify and generalize Module links

addon/routes/docs/api/item.js, lib/broccoli/docs-compiler.js, sandbox/app/components/simple-list/component.js, sandbox/app/components/simple-list/item/component.js, tests/acceptance/sandbox/api/components-test.js
Enables documenting nested components and fixes to components with similar names
Fixes #94
=> [bugfix] Enable nested components

.travis.yml, package.json, tests/acceptance/sandbox/api/components-test.js, yarn.lock
I'll kick Travis once or twice more to be sure, but this takes care of all the intermittent failures I'm aware of that we've been seeing lately.
=> Try and get tests into a more stable place

addon/components/docs-viewer/x-main/component.js
I have file `"templates/docs/index.md"` and path `"templates/docs/index.md"`
I need the file to be resolved for this path.
=> fix regex in x-main

tests/dummy/app/pods/docs/usage/template.md
=> Document supported Ember version

package.json, yarn.lock
=> Update ember-data to the latest version

ember-cli-build.js
This will close #255. For anyone who happens across this because of errors in their own project, the root issue (and lots more details about it) is https://github.com/terser-js/terser/issues/120
=> Fix production builds

addon/components/docs-header/version-selector/component.js, tests/acceptance/version-selector-test.js, tests/dummy/app/app.js
i literally have no idea how this test ever passed
=> Fix version selector test

lib/broccoli/docs-compiler/navigation-index-generator.js, tests-node/unit/navigation-index-generator/test.js
=> Fix resolved type on module name containing type itself

addon/components/docs-header/template.hbs
This is just an updated version of #271, because I'm currently blocked by this issue and would like it to land.
=> Fix usage of a test selector on a tagless component

addon/components/api/x-section/template.hbs, addon/components/docs-header/search-result/component.js, addon/components/docs-viewer/x-main/component.js, addon/components/docs-viewer/x-main/template.hbs, index.js, tests/acceptance/sandbox/api/components-test.js, yarn.lock
A few small fixes for things I've run into working on documenting a few packages (of which one is an addon) in a monorepo. Among other things, I think this should fix the icons on http://ember-decorators.github.io/ember-decorators
=> Fix icons and edit links for monorepo addons

package.json, yarn.lock
Two commits, two simple upgrades.
This adjustement would close https://github.com/ember-learn/ember-cli-addon-docs/issues/373
=> Upgrade concurrency + liquid-fire

addon/routes/docs/api/item.js
=> Fix nested components API doc routing

blueprints/docs-page/index.js
=> Make blueprint compatible with angle brackets

package.json, yarn.lock
Bump ember-code-snippet version to use latest
=> Bump ember-code-snippet from 2.4.0 to 2.4.1

addon/utils/compile-markdown.js, tests-node/unit/utils/compile-markdown-test.js
Closes https://github.com/ember-learn/ember-cli-addon-docs/issues/360
=> Fix compacting of paragraphs containing self-closing angle bracket components

addon/initializers/route-anchor-jump.js, app/initializers/route-anchor-jump.js
=> fix: scroll hash anchor into view

addon/components/docs-header/template.hbs
After reading the code, I detect an useless or in a condition so here is a tiny PR to clean the code :)
=> Update docs-header template to remove an useless "or" in a condition

addon/components/docs-hero/component.js
=> docs-hero: Fix YUIDoc property name logo→prefix to match actual property name

addon/components/docs-viewer/x-nav/component.js, addon/services/project-version.js
see https://emberjs.com/deprecations/v3.x#toc_computed-property-override
=> fix deprecation computed-property.override by adding setters

addon/utils/compile-markdown.js
=> Adds tailwind list style classes

addon/styles/addon.scss, addon/styles/components/_docs-header-search-box.scss, addon/styles/components/_modal-dialog.scss
=> Remove brand bg color

addon/utils/compile-markdown.js
=> Fix highlightjs deprecation

package.json, yarn.lock
- [broccoli-debug](https://github.com/broccolijs/broccoli-debug)
- Added in https://github.com/ember-learn/ember-cli-addon-docs/pull/247 via this commit https://github.com/ember-learn/ember-cli-addon-docs/pull/247/commits/9de2b590407c0b21cf21d40241716fd63996e8bf
- Not used since the same PR https://github.com/ember-learn/ember-cli-addon-docs/pull/247
- [inflected](https://github.com/martinandert/inflected)
- Added in https://github.com/ember-learn/ember-cli-addon-docs/commit/2d0e288f9cb223f7fbe680aeaf4f37d96250ef58#diff-48394617c0240fb029fa5459bf8a84c5a7a5e64588344681183a41bf60e647fbR9
- Not used since https://github.com/ember-learn/ember-cli-addon-docs/commit/0561c3d9d82946b6f0c68adf646010c494d3488a#diff-d34fb7527260048f2ddde586f0d54dbce0ccb6dda8093c96dcedaa8ea8688a8cL8
- …
=> build: remove some unused deps / devDeps

addon/components/api/x-class/index.js, addon/components/api/x-component/index.hbs, addon/components/api/x-component/index.js, addon/components/api/x-section/index.js, addon/components/api/x-toggles.hbs, addon/router.js, addon/utils/compile-markdown.js, addon/utils/computed.js, sandbox/app/components/yuidoc-component.js, test-apps/new-addon/addon/components/some-component.js, tests/dummy/app/templates/docs/components/docs-snippet.md
This shouldn't introduce any breaking changes since all these components are only used internally.
=> update api components

addon/-private/config.js, addon/adapters/-addon-docs.js, addon/components/api/x-class/index.hbs, addon/components/api/x-class/index.js, addon/components/api/x-section/index.hbs, addon/components/api/x-section/index.js, addon/components/docs-header/index.hbs, addon/components/docs-header/index.js, addon/components/docs-header/search-box/index.js, addon/components/docs-header/search-results/index.js, addon/components/docs-header/version-selector/index.hbs, addon/components/docs-header/version-selector/index.js, addon/components/docs-hero/index.js, addon/components/docs-viewer/x-main/index.js, addon/components/docs-viewer/x-nav/index.js, addon/routes/docs.js, addon/services/docs-search.js, addon/services/project-version.js, package.json, tests/acceptance/sandbox/api/components-test.js, tests/dummy/mirage/config.js, yarn.lock
Follow up of our discussion on #1137
=> chore(config): remove all usage of ember-get-config

package.json, yarn.lock
Adds explicit Ember 4 support and native Ember types
=> ember-concurrency v3

package.json, yarn.lock
somehow latest version stopped working with embroider. might also be an issue with latest embroider? https://github.com/embroider-build/embroider/releases/tag/v3.1.4-compat
=> pin ember-svg-jar to fix Embroider build
